// <auto-generated />
using System;
using ASEDUPH_V2_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASEDUPH_V2_API.Migrations
{
    [DbContext(typeof(AseduphDbContext))]
    [Migration("20260619202641_CrearTablasFaltantes")]
    partial class CrearTablasFaltantes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Aporte", b =>
                {
                    b.Property<int>("AporteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AporteId"));

                    b.Property<int?>("BecaId")
                        .HasColumnType("int");

                    b.Property<int>("BenefactorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAporte")
                        .HasColumnType("datetime2");

                    b.Property<string>("FormaPago")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NumeroComprobante")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Periodo")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TipoAporte")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("AporteId");

                    b.HasIndex("BecaId");

                    b.HasIndex("BenefactorId");

                    b.ToTable("Aportes");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.ApoyoExterno", b =>
                {
                    b.Property<int>("ApoyoExternoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApoyoExternoId"));

                    b.Property<string>("Institucion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreBeneficiado")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parentesco")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal?>("PorcentajeApoyo")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool?>("TerminoEstudios")
                        .HasColumnType("bit");

                    b.Property<string>("TipoAyuda")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VisitaFamiliarId")
                        .HasColumnType("int");

                    b.HasKey("ApoyoExternoId");

                    b.HasIndex("VisitaFamiliarId");

                    b.ToTable("ApoyosExternos");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Beca", b =>
                {
                    b.Property<int>("BecaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BecaId"));

                    b.Property<int?>("AnioFin")
                        .HasColumnType("int");

                    b.Property<int>("AnioInicio")
                        .HasColumnType("int");

                    b.Property<string>("EstadoBeca")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("MontoAprobado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NivelEducativo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SolicitudBecaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoBeca")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("BecaId");

                    b.HasIndex("EstudianteId");

                    b.HasIndex("SolicitudBecaId");

                    b.ToTable("Becas");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Benefactor", b =>
                {
                    b.Property<int>("BenefactorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenefactorId"));

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoBenefactor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BenefactorId");

                    b.ToTable("Benefactores");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.BienFamiliar", b =>
                {
                    b.Property<int>("BienFamiliarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BienFamiliarId"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoBien")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("VisitaFamiliarId")
                        .HasColumnType("int");

                    b.HasKey("BienFamiliarId");

                    b.HasIndex("VisitaFamiliarId");

                    b.ToTable("BienesFamiliares");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.CentroEducativo", b =>
                {
                    b.Property<int>("CentroEducativoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CentroEducativoId"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoCentro")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CentroEducativoId");

                    b.ToTable("CentrosEducativos");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Encargado", b =>
                {
                    b.Property<int>("EncargadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EncargadoId"));

                    b.Property<string>("CorreoElectronico")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("DPI")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("DpiExtendido")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<string>("LugarTrabajo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Ocupacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Parentesco")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefonoCelular")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelefonoDomiciliar")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TelefonoTrabajo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EncargadoId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("Encargados");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Estudiante", b =>
                {
                    b.Property<int>("EstudianteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstudianteId"));

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Municipio")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EstudianteId");

                    b.ToTable("Estudiantes");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.EvaluacionBeca", b =>
                {
                    b.Property<int>("EvaluacionBecaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EvaluacionBecaId"));

                    b.Property<string>("ClasificacionOtorgada")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("DecisionFinal")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EvaluadoPor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("FechaDecision")
                        .HasColumnType("datetime2");

                    b.Property<string>("ObservacionesGenerales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecomendacionesResponsable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitudBecaId")
                        .HasColumnType("int");

                    b.HasKey("EvaluacionBecaId");

                    b.HasIndex("SolicitudBecaId")
                        .IsUnique();

                    b.ToTable("EvaluacionesBeca");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.GrupoFamiliar", b =>
                {
                    b.Property<int>("GrupoFamiliarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrupoFamiliarId"));

                    b.Property<int?>("Edad")
                        .HasColumnType("int");

                    b.Property<decimal?>("GastosColegiatura")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Ingresos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("LugarTrabajoEstudio")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Parentesco")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("VisitaFamiliarId")
                        .HasColumnType("int");

                    b.Property<bool?>("ViveConFamilia")
                        .HasColumnType("bit");

                    b.HasKey("GrupoFamiliarId");

                    b.HasIndex("VisitaFamiliarId");

                    b.ToTable("GrupoFamiliar");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.ListaCotejoEvaluacion", b =>
                {
                    b.Property<int>("ListaCotejoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListaCotejoId"));

                    b.Property<bool>("Completado")
                        .HasColumnType("bit");

                    b.Property<int>("EvaluacionBecaId")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Rubro")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("ListaCotejoId");

                    b.HasIndex("EvaluacionBecaId");

                    b.ToTable("ListaCotejoEvaluacion");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.LogAuditoria", b =>
                {
                    b.Property<int>("LogAuditoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogAuditoriaId"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntidadAfectada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntidadId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resultado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("LogAuditoriaId");

                    b.ToTable("LogsAuditoria");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.RenovacionBeca", b =>
                {
                    b.Property<int>("RenovacionBecaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RenovacionBecaId"));

                    b.Property<string>("AnioACursar")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AnioCursadoAnterior")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AnioRenovacion")
                        .HasColumnType("int");

                    b.Property<int>("BecaId")
                        .HasColumnType("int");

                    b.Property<int?>("CentroEducativoAnteriorId")
                        .HasColumnType("int");

                    b.Property<int?>("CentroEducativoNuevoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoRenovacion")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime?>("FechaDecision")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoRenovacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PromedioFinalAnterior")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Recomendaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoApoyoRecibido")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("RenovacionBecaId");

                    b.HasIndex("BecaId");

                    b.HasIndex("CentroEducativoAnteriorId");

                    b.HasIndex("CentroEducativoNuevoId");

                    b.ToTable("RenovacionesBeca");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.SeguimientoAcademico", b =>
                {
                    b.Property<int>("SeguimientoAcademicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeguimientoAcademicoId"));

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int?>("BecaId")
                        .HasColumnType("int");

                    b.Property<int?>("CentroEducativoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoAcademico")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NivelEducativo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Promedio")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("SeguimientoAcademicoId");

                    b.HasIndex("BecaId");

                    b.HasIndex("CentroEducativoId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("SeguimientoAcademico");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.SituacionEconomica", b =>
                {
                    b.Property<int>("SituacionEconomicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SituacionEconomicaId"));

                    b.Property<string>("DescripcionEndeudamiento")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("GastoAgua")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GastoAhorro")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GastoAlimentacion")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GastoDiversion")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GastoEducacion")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GastoLuz")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GastoSalud")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GastoTelefono")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GastoTransporte")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("GastoVivienda")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OtrosGastos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool?>("TieneCreditoBancario")
                        .HasColumnType("bit");

                    b.Property<bool?>("TieneEndeudamiento")
                        .HasColumnType("bit");

                    b.Property<bool?>("TieneTarjetaCredito")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TotalEgresos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("TotalIngresos")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("VisitaFamiliarId")
                        .HasColumnType("int");

                    b.HasKey("SituacionEconomicaId");

                    b.HasIndex("VisitaFamiliarId")
                        .IsUnique();

                    b.ToTable("SituacionEconomica");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.SolicitudBeca", b =>
                {
                    b.Property<int>("SolicitudBecaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudBecaId"));

                    b.Property<int>("AnioSolicitud")
                        .HasColumnType("int");

                    b.Property<int?>("CentroEducativoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoSolicitud")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("EstudianteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaFormulario")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("GradoSolicitado")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MotivoSolicitud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NivelEducativo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombrePersonaCompletaFormulario")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PromedioActual")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("SolicitudBecaId");

                    b.HasIndex("CentroEducativoId");

                    b.HasIndex("EstudianteId");

                    b.ToTable("SolicitudesBeca");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.SolicitudTipoApoyo", b =>
                {
                    b.Property<int>("SolicitudTipoApoyoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudTipoApoyoId"));

                    b.Property<string>("DescripcionOtroApoyo")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("MontoEstimado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("SolicitudBecaId")
                        .HasColumnType("int");

                    b.Property<int>("TipoApoyoId")
                        .HasColumnType("int");

                    b.HasKey("SolicitudTipoApoyoId");

                    b.HasIndex("SolicitudBecaId");

                    b.HasIndex("TipoApoyoId");

                    b.ToTable("SolicitudTiposApoyo");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.TipoApoyo", b =>
                {
                    b.Property<int>("TipoApoyoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoApoyoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TipoApoyoId");

                    b.ToTable("TiposApoyo");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Correo")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.UsuarioRol", b =>
                {
                    b.Property<int>("UsuarioRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioRolId"));

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioRolId");

                    b.HasIndex("RolId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioRoles");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.VisitaFamiliar", b =>
                {
                    b.Property<int>("VisitaFamiliarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitaFamiliarId"));

                    b.Property<string>("ActitudFamilia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApreciacionGeneral")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaVisita")
                        .HasColumnType("datetime2");

                    b.Property<string>("Firma")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<TimeSpan?>("HoraVisita")
                        .HasColumnType("time");

                    b.Property<string>("LugarEntrevista")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ObservacionesFinales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentescoEntrevistado")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PersonaEntrevistada")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RealizadaPor")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RecomendacionJunta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitudBecaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoVisita")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VisitaFamiliarId");

                    b.HasIndex("SolicitudBecaId")
                        .IsUnique();

                    b.ToTable("VisitasFamiliares");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Vivienda", b =>
                {
                    b.Property<int>("ViviendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViviendaId"));

                    b.Property<decimal?>("AmortizacionMensual")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("DescripcionVivienda")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("MostroRecibo")
                        .HasColumnType("bit");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PagoMensual")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoVivienda")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VisitaFamiliarId")
                        .HasColumnType("int");

                    b.HasKey("ViviendaId");

                    b.HasIndex("VisitaFamiliarId")
                        .IsUnique();

                    b.ToTable("Viviendas");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Aporte", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.Beca", "Beca")
                        .WithMany("Aportes")
                        .HasForeignKey("BecaId");

                    b.HasOne("ASEDUPH_V2_API.Models.Benefactor", "Benefactor")
                        .WithMany("Aportes")
                        .HasForeignKey("BenefactorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beca");

                    b.Navigation("Benefactor");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.ApoyoExterno", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.VisitaFamiliar", "VisitaFamiliar")
                        .WithMany("ApoyosExternos")
                        .HasForeignKey("VisitaFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitaFamiliar");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Beca", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.Estudiante", "Estudiante")
                        .WithMany("Becas")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASEDUPH_V2_API.Models.SolicitudBeca", "SolicitudBeca")
                        .WithMany()
                        .HasForeignKey("SolicitudBecaId");

                    b.Navigation("Estudiante");

                    b.Navigation("SolicitudBeca");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.BienFamiliar", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.VisitaFamiliar", "VisitaFamiliar")
                        .WithMany("BienesFamiliares")
                        .HasForeignKey("VisitaFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitaFamiliar");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Encargado", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.Estudiante", "Estudiante")
                        .WithMany("Encargados")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.EvaluacionBeca", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.SolicitudBeca", "SolicitudBeca")
                        .WithOne("EvaluacionBeca")
                        .HasForeignKey("ASEDUPH_V2_API.Models.EvaluacionBeca", "SolicitudBecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitudBeca");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.GrupoFamiliar", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.VisitaFamiliar", "VisitaFamiliar")
                        .WithMany("GrupoFamiliar")
                        .HasForeignKey("VisitaFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitaFamiliar");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.ListaCotejoEvaluacion", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.EvaluacionBeca", "EvaluacionBeca")
                        .WithMany()
                        .HasForeignKey("EvaluacionBecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluacionBeca");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.RenovacionBeca", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.Beca", "Beca")
                        .WithMany("RenovacionesBeca")
                        .HasForeignKey("BecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASEDUPH_V2_API.Models.CentroEducativo", "CentroEducativoAnterior")
                        .WithMany()
                        .HasForeignKey("CentroEducativoAnteriorId");

                    b.HasOne("ASEDUPH_V2_API.Models.CentroEducativo", "CentroEducativoNuevo")
                        .WithMany()
                        .HasForeignKey("CentroEducativoNuevoId");

                    b.Navigation("Beca");

                    b.Navigation("CentroEducativoAnterior");

                    b.Navigation("CentroEducativoNuevo");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.SeguimientoAcademico", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.Beca", "Beca")
                        .WithMany("SeguimientosAcademicos")
                        .HasForeignKey("BecaId");

                    b.HasOne("ASEDUPH_V2_API.Models.CentroEducativo", "CentroEducativo")
                        .WithMany("SeguimientosAcademicos")
                        .HasForeignKey("CentroEducativoId");

                    b.HasOne("ASEDUPH_V2_API.Models.Estudiante", "Estudiante")
                        .WithMany("SeguimientosAcademicos")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Beca");

                    b.Navigation("CentroEducativo");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.SituacionEconomica", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.VisitaFamiliar", "VisitaFamiliar")
                        .WithOne("SituacionEconomica")
                        .HasForeignKey("ASEDUPH_V2_API.Models.SituacionEconomica", "VisitaFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitaFamiliar");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.SolicitudBeca", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.CentroEducativo", "CentroEducativo")
                        .WithMany("SolicitudesBeca")
                        .HasForeignKey("CentroEducativoId");

                    b.HasOne("ASEDUPH_V2_API.Models.Estudiante", "Estudiante")
                        .WithMany("SolicitudesBeca")
                        .HasForeignKey("EstudianteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentroEducativo");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.SolicitudTipoApoyo", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.SolicitudBeca", "SolicitudBeca")
                        .WithMany("SolicitudTiposApoyo")
                        .HasForeignKey("SolicitudBecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASEDUPH_V2_API.Models.TipoApoyo", "TipoApoyo")
                        .WithMany("SolicitudTiposApoyo")
                        .HasForeignKey("TipoApoyoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitudBeca");

                    b.Navigation("TipoApoyo");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.UsuarioRol", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASEDUPH_V2_API.Models.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.VisitaFamiliar", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.SolicitudBeca", "SolicitudBeca")
                        .WithOne("VisitaFamiliar")
                        .HasForeignKey("ASEDUPH_V2_API.Models.VisitaFamiliar", "SolicitudBecaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SolicitudBeca");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Vivienda", b =>
                {
                    b.HasOne("ASEDUPH_V2_API.Models.VisitaFamiliar", "VisitaFamiliar")
                        .WithOne("Vivienda")
                        .HasForeignKey("ASEDUPH_V2_API.Models.Vivienda", "VisitaFamiliarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitaFamiliar");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Beca", b =>
                {
                    b.Navigation("Aportes");

                    b.Navigation("RenovacionesBeca");

                    b.Navigation("SeguimientosAcademicos");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Benefactor", b =>
                {
                    b.Navigation("Aportes");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.CentroEducativo", b =>
                {
                    b.Navigation("SeguimientosAcademicos");

                    b.Navigation("SolicitudesBeca");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Estudiante", b =>
                {
                    b.Navigation("Becas");

                    b.Navigation("Encargados");

                    b.Navigation("SeguimientosAcademicos");

                    b.Navigation("SolicitudesBeca");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Rol", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.SolicitudBeca", b =>
                {
                    b.Navigation("EvaluacionBeca");

                    b.Navigation("SolicitudTiposApoyo");

                    b.Navigation("VisitaFamiliar");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.TipoApoyo", b =>
                {
                    b.Navigation("SolicitudTiposApoyo");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("ASEDUPH_V2_API.Models.VisitaFamiliar", b =>
                {
                    b.Navigation("ApoyosExternos");

                    b.Navigation("BienesFamiliares");

                    b.Navigation("GrupoFamiliar");

                    b.Navigation("SituacionEconomica");

                    b.Navigation("Vivienda");
                });
#pragma warning restore 612, 618
        }
    }
}
